#!/usr/bin/env python3
"""
curate-training-data.py

Filters and scores raw training data generated by generate-training-data.sh.
Produces a curated JSONL file ready for LoRA fine-tuning with unsloth/axolotl.

Usage:
    python3 scripts/curate-training-data.py [input.jsonl] [output.jsonl]

Filtering criteria:
    - Response length >= 10 characters
    - No hallucinated entities (if grounding.json exists)
    - No duplicate or near-duplicate responses
    - No instruction leakage (PERSONALITY:, SYSTEM:, etc.)

Scoring criteria:
    - Response length variety (not all same length)
    - Lore reference count
    - Personality consistency
"""

import json
import sys
import os
from collections import defaultdict
from pathlib import Path


def load_grounding(data_dir: str) -> dict | None:
    """Load grounding.json for entity validation."""
    path = Path(data_dir) / "grounding.json"
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def has_instruction_leak(text: str) -> bool:
    """Check for instruction leakage in response text."""
    leak_patterns = [
        "PERSONALITY:", "WORLD KNOWLEDGE:", "MEMORY:", "INSTRUCTIONS:",
        "SYSTEM:", "CONTEXT:", "NOTE:", "GROUNDING:",
        "Do NOT reference", "never invent others",
    ]
    upper = text.upper()
    return any(p.upper() in upper for p in leak_patterns)


def has_hallucinated_entity(text: str, grounding: dict) -> bool:
    """Basic check for obviously hallucinated zone names."""
    if not grounding:
        return False

    known_zones = set(z.lower() for z in grounding.get("zones", []))

    # Look for "in <Zone Name>" patterns that don't match known zones
    import re
    zone_refs = re.findall(r'\bin\s+([A-Z][a-z]+(?:\'s)?\s+[A-Z][a-z]+(?:\'s)?)', text)
    for ref in zone_refs:
        if ref.lower() not in known_zones:
            # Check if it's close to any known zone (simple substring check)
            close = any(ref.lower() in z or z in ref.lower() for z in known_zones)
            if not close:
                return True

    return False


def normalize_text(text: str) -> str:
    """Normalize text for deduplication."""
    return " ".join(text.lower().split())


def curate(input_path: str, output_path: str, data_dir: str):
    """Filter and score training examples."""
    grounding = load_grounding(data_dir)

    examples = []
    with open(input_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                examples.append(json.loads(line))
            except json.JSONDecodeError:
                continue

    print(f"Loaded {len(examples)} raw examples")

    # Filtering
    filtered = []
    seen_responses = set()
    stats = defaultdict(int)

    for ex in examples:
        msgs = ex.get("messages", [])
        if len(msgs) < 3:
            stats["incomplete"] += 1
            continue

        response = msgs[2].get("content", "")
        user_msg = msgs[1].get("content", "")

        # Length filter
        if len(response) < 10:
            stats["too_short"] += 1
            continue

        # Instruction leak filter
        if has_instruction_leak(response):
            stats["instruction_leak"] += 1
            continue

        # Hallucination filter
        if has_hallucinated_entity(response, grounding):
            stats["hallucinated"] += 1
            continue

        # Deduplication (exact normalized match)
        normalized = normalize_text(response)
        if normalized in seen_responses:
            stats["duplicate"] += 1
            continue
        seen_responses.add(normalized)

        # Score the example
        score = 0.0

        # Length score: prefer responses between 30-200 chars
        if 30 <= len(response) <= 200:
            score += 1.0
        elif len(response) > 200:
            score += 0.5

        # Lore reference bonus: mentions specific game entities
        if grounding:
            zones = grounding.get("zones", [])
            classes = grounding.get("classes", [])
            for zone in zones:
                if zone in response:
                    score += 0.5
                    break
            for cls in classes:
                if cls in response:
                    score += 0.3
                    break

        # Personality consistency: response should sound different from input
        if normalized != normalize_text(user_msg):
            score += 0.2

        # Sentence completeness
        if response.rstrip()[-1:] in ".!?":
            score += 0.3

        ex["score"] = score
        filtered.append(ex)

    # Sort by score descending
    filtered.sort(key=lambda x: x.get("score", 0), reverse=True)

    # Write curated output (remove metadata and score for training)
    with open(output_path, "w") as f:
        for ex in filtered:
            training_ex = {"messages": ex["messages"]}
            f.write(json.dumps(training_ex) + "\n")

    # Report
    print(f"\n=== Curation Report ===")
    print(f"Input:     {len(examples)}")
    print(f"Output:    {len(filtered)}")
    print(f"Filtered out:")
    for reason, count in sorted(stats.items()):
        print(f"  {reason}: {count}")
    print(f"\nScore distribution:")
    if filtered:
        scores = [ex.get("score", 0) for ex in filtered]
        print(f"  Min: {min(scores):.1f}")
        print(f"  Max: {max(scores):.1f}")
        print(f"  Avg: {sum(scores)/len(scores):.1f}")
    print(f"\nOutput written to: {output_path}")

    # Per-personality stats
    sim_counts = defaultdict(int)
    for ex in filtered:
        meta = ex.get("metadata", {})
        sim_counts[meta.get("sim_name", "unknown")] += 1

    print(f"\nPer-personality counts (top 10):")
    for sim, count in sorted(sim_counts.items(), key=lambda x: -x[1])[:10]:
        print(f"  {sim}: {count}")


if __name__ == "__main__":
    input_file = sys.argv[1] if len(sys.argv) > 1 else "training-data-raw.jsonl"
    output_file = sys.argv[2] if len(sys.argv) > 2 else "training-data-curated.jsonl"

    # Find data dir relative to script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(script_dir, "..", "data")

    if not os.path.exists(input_file):
        print(f"ERROR: Input file not found: {input_file}")
        print(f"Run generate-training-data.sh first.")
        sys.exit(1)

    curate(input_file, output_file, data_dir)
